name: Build Web3Modal

on:
  push:
     paths:
      - "**/**"
      - "!**/*.md/**"

env:
  CI: true
  FORCE_COLOR: 2

jobs:
  pipeline:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: ['14.x', '16.x']
        os: ['ubuntu-latest', 'macos-latest']

    steps:
      - name: Clone repository
        uses: actions/checkout@v2.3.5

      - name: Set up Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node }}

          
      - name: Install truffle
        run: |
          yarn install -g truffle --unsafe-perm
      - name: Build library
        run: |
          echo "SKIP_PREFLIGHT_CHECK=true" > .env
          yarn run bootstrap
          npm run build
        env:
          CI: true
          NODE_OPTIONS: --max_old_space_size=5120
      - name: Build example
        run: |
          echo "SKIP_PREFLIGHT_CHECK=true" > example/.env
          yarn run build:example
        env:
          NODE_OPTIONS: --max_old_space_size=5120
